name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: create firebase config file 
        run: | 
           cd 
           mkdir lib/backend/firebase 
           echo "creating firebase_config.dart"
           echo "import 'package:firebase_core/firebase_core.dart';" > lib/backend/firebase/firebase_config.dart
           echo "import 'package:flutter/foundation.dart';" >>  lib/backend/firebase/firebase_config.dart
           cat lib/backend/firebase/firebase_config.dart
           
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          
      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build Flutter for web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project my-demo-app-dev-9f4c3
